name: docker

on:
  push:
    branches: ["main"]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker buildx build --platform linux/amd64 -t ghcr.io/iplantalks/talks:latest .
      - run: docker push ghcr.io/iplantalks/talks
